// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: wifi-test

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void coffee_connect_wifi(lv_event_t* e);
void coffee_send_ok(lv_event_t* e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
