// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: wifi-test

#include "ui.h"

#include <network_task.hpp>

extern "C" {
    void coffee_connect_wifi(lv_event_t* e) {
        coffee::connect_wifi(lv_textarea_get_text(ui_ssidTextArea), lv_textarea_get_text(ui_pwTextArea));
    }

    void coffee_send_ok(lv_event_t* e) {
        coffee::send_ok();
    }
}
