// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: wifi-test

#ifndef UI_MAINSCREEN_H
#define UI_MAINSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_mainScreen
extern void ui_mainScreen_screen_init(void);
extern void ui_mainScreen_screen_destroy(void);
extern lv_obj_t * ui_mainScreen;
extern lv_obj_t * ui_title;
extern void ui_event_connectButton(lv_event_t * e);
extern lv_obj_t * ui_connectButton;
extern lv_obj_t * ui_connectButtonLabel;
extern lv_obj_t * ui_ssidContainer;
extern lv_obj_t * ui_ssidLabel;
extern void ui_event_ssidTextArea(lv_event_t * e);
extern lv_obj_t * ui_ssidTextArea;
extern lv_obj_t * ui_pwContainer;
extern lv_obj_t * ui_pwLabel;
extern void ui_event_pwTextArea(lv_event_t * e);
extern lv_obj_t * ui_pwTextArea;
extern lv_obj_t * ui_chatTextArea;
extern void ui_event_sendButton(lv_event_t * e);
extern lv_obj_t * ui_sendButton;
extern lv_obj_t * ui_sendLabel;
extern lv_obj_t * ui_keyboard;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

