// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: sql-coffee-candy

#ifndef _SQL_COFFEE_CANDY_UI_H
#define _SQL_COFFEE_CANDY_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

///////////////////// SCREENS ////////////////////

#include "ui_mainScreen.h"
#include "ui_flavorScreen.h"
#include "ui_configScreen.h"
#include "ui_dropScreen.h"
#include "ui_dropDoneScreen.h"
#include "ui_wifiScreen.h"
#include "ui_serverScreen.h"
#include "ui_firmwareScreen.h"
#include "ui_debugScreen.h"

///////////////////// VARIABLES ////////////////////

extern lv_anim_t * keyboardDownAnimation_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * keyboardUpAnimation_Animation(lv_obj_t * TargetObject, int delay);

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
