// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: sql-coffee-candy

#include "ui.h"

lv_obj_t * ui_configScreen = NULL;
lv_obj_t * ui_configLabel = NULL;
lv_obj_t * ui_configWifiButton = NULL;
lv_obj_t * ui_configWifiImage = NULL;
lv_obj_t * ui_configWifiLabel = NULL;
lv_obj_t * ui_configSeverButton = NULL;
lv_obj_t * ui_configServerImage = NULL;
lv_obj_t * ui_configServerLabel = NULL;
lv_obj_t * ui_configFirmwareButton = NULL;
lv_obj_t * ui_configFirmwareImage = NULL;
lv_obj_t * ui_configFirmwareLabel = NULL;
lv_obj_t * ui_configBackButton = NULL;
lv_obj_t * ui_configBackImage = NULL;
// event funtions
void ui_event_configScreen(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOAD_START) {
        config_screen_load(e);
    }
}

void ui_event_configWifiButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_RELEASED) {
        _ui_screen_change(&ui_wifiScreen, LV_SCR_LOAD_ANIM_OVER_BOTTOM, 500, 0, &ui_wifiScreen_screen_init);
        _ui_screen_delete(&ui_configScreen);
    }
}

void ui_event_configSeverButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_RELEASED) {
        _ui_screen_change(&ui_serverScreen, LV_SCR_LOAD_ANIM_OVER_BOTTOM, 500, 0, &ui_serverScreen_screen_init);
        _ui_screen_delete(&ui_configScreen);
    }
}

void ui_event_configFirmwareButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_RELEASED) {
        _ui_screen_change(&ui_firmwareScreen, LV_SCR_LOAD_ANIM_OVER_BOTTOM, 500, 0, &ui_firmwareScreen_screen_init);
        _ui_screen_delete(&ui_configScreen);
    }
}

void ui_event_configBackButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_RELEASED) {
        _ui_screen_change(&ui_mainScreen, LV_SCR_LOAD_ANIM_OVER_BOTTOM, 500, 0, &ui_mainScreen_screen_init);
        _ui_screen_delete(&ui_configScreen);
    }
}

// build funtions

void ui_configScreen_screen_init(void)
{
    ui_configScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_configScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_configLabel = lv_label_create(ui_configScreen);
    lv_obj_set_height(ui_configLabel, 42);
    lv_obj_set_width(ui_configLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_configLabel, 0);
    lv_obj_set_y(ui_configLabel, -140);
    lv_obj_set_align(ui_configLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_configLabel, "Config");
    lv_obj_set_style_text_font(ui_configLabel, &lv_font_montserrat_42, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_configWifiButton = lv_btn_create(ui_configScreen);
    lv_obj_set_width(ui_configWifiButton, 200);
    lv_obj_set_height(ui_configWifiButton, 200);
    lv_obj_set_x(ui_configWifiButton, -250);
    lv_obj_set_y(ui_configWifiButton, 40);
    lv_obj_set_align(ui_configWifiButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_configWifiButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_configWifiButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_configWifiButton, lv_color_hex(0xE8E8E8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_configWifiButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_configWifiButton, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_configWifiButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_configWifiButton, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_configWifiButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_configWifiImage = lv_img_create(ui_configWifiButton);
    lv_obj_set_width(ui_configWifiImage, 100);
    lv_obj_set_height(ui_configWifiImage, 100);
    lv_obj_set_x(ui_configWifiImage, 0);
    lv_obj_set_y(ui_configWifiImage, -19);
    lv_obj_set_align(ui_configWifiImage, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_configWifiImage, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_configWifiImage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_configWifiLabel = lv_label_create(ui_configWifiButton);
    lv_obj_set_height(ui_configWifiLabel, 28);
    lv_obj_set_width(ui_configWifiLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_configWifiLabel, 0);
    lv_obj_set_y(ui_configWifiLabel, 55);
    lv_obj_set_align(ui_configWifiLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_configWifiLabel, "Wi-Fi");
    lv_obj_set_style_text_color(ui_configWifiLabel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_configWifiLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_configWifiLabel, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_configSeverButton = lv_btn_create(ui_configScreen);
    lv_obj_set_width(ui_configSeverButton, 200);
    lv_obj_set_height(ui_configSeverButton, 200);
    lv_obj_set_x(ui_configSeverButton, 0);
    lv_obj_set_y(ui_configSeverButton, 40);
    lv_obj_set_align(ui_configSeverButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_configSeverButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_configSeverButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_configSeverButton, lv_color_hex(0xE8E8E8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_configSeverButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_configSeverButton, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_configSeverButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_configSeverButton, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_configSeverButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_configServerImage = lv_img_create(ui_configSeverButton);
    lv_obj_set_width(ui_configServerImage, 100);
    lv_obj_set_height(ui_configServerImage, 100);
    lv_obj_set_x(ui_configServerImage, 0);
    lv_obj_set_y(ui_configServerImage, -19);
    lv_obj_set_align(ui_configServerImage, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_configServerImage, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_configServerImage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_configServerLabel = lv_label_create(ui_configSeverButton);
    lv_obj_set_height(ui_configServerLabel, 28);
    lv_obj_set_width(ui_configServerLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_configServerLabel, -1);
    lv_obj_set_y(ui_configServerLabel, 55);
    lv_obj_set_align(ui_configServerLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_configServerLabel, "SERVER");
    lv_obj_set_style_text_color(ui_configServerLabel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_configServerLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_configServerLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_configServerLabel, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_configFirmwareButton = lv_btn_create(ui_configScreen);
    lv_obj_set_width(ui_configFirmwareButton, 200);
    lv_obj_set_height(ui_configFirmwareButton, 200);
    lv_obj_set_x(ui_configFirmwareButton, 250);
    lv_obj_set_y(ui_configFirmwareButton, 40);
    lv_obj_set_align(ui_configFirmwareButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_configFirmwareButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_configFirmwareButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_configFirmwareButton, lv_color_hex(0xE8E8E8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_configFirmwareButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_configFirmwareButton, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_configFirmwareButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_configFirmwareButton, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_configFirmwareButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_configFirmwareImage = lv_img_create(ui_configFirmwareButton);
    lv_obj_set_width(ui_configFirmwareImage, 100);
    lv_obj_set_height(ui_configFirmwareImage, 100);
    lv_obj_set_x(ui_configFirmwareImage, 0);
    lv_obj_set_y(ui_configFirmwareImage, -19);
    lv_obj_set_align(ui_configFirmwareImage, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_configFirmwareImage, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_configFirmwareImage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_configFirmwareLabel = lv_label_create(ui_configFirmwareButton);
    lv_obj_set_height(ui_configFirmwareLabel, 28);
    lv_obj_set_width(ui_configFirmwareLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_configFirmwareLabel, 0);
    lv_obj_set_y(ui_configFirmwareLabel, 55);
    lv_obj_set_align(ui_configFirmwareLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_configFirmwareLabel, "FIRMWARE");
    lv_obj_set_style_text_color(ui_configFirmwareLabel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_configFirmwareLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_configFirmwareLabel, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_configBackButton = lv_btn_create(ui_configScreen);
    lv_obj_set_width(ui_configBackButton, 60);
    lv_obj_set_height(ui_configBackButton, 60);
    lv_obj_set_x(ui_configBackButton, 360);
    lv_obj_set_y(ui_configBackButton, 200);
    lv_obj_set_align(ui_configBackButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_configBackButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_configBackButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_configBackButton, lv_color_hex(0xE8E8E8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_configBackButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_configBackButton, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_configBackButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_configBackButton, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_configBackButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_configBackImage = lv_img_create(ui_configBackButton);
    lv_obj_set_width(ui_configBackImage, 50);
    lv_obj_set_height(ui_configBackImage, 50);
    lv_obj_set_align(ui_configBackImage, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_configBackImage, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_configBackImage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_configWifiButton, ui_event_configWifiButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_configSeverButton, ui_event_configSeverButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_configFirmwareButton, ui_event_configFirmwareButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_configBackButton, ui_event_configBackButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_configScreen, ui_event_configScreen, LV_EVENT_ALL, NULL);

}

void ui_configScreen_screen_destroy(void)
{
    if(ui_configScreen) lv_obj_del(ui_configScreen);

    // NULL screen variables
    ui_configScreen = NULL;
    ui_configLabel = NULL;
    ui_configWifiButton = NULL;
    ui_configWifiImage = NULL;
    ui_configWifiLabel = NULL;
    ui_configSeverButton = NULL;
    ui_configServerImage = NULL;
    ui_configServerLabel = NULL;
    ui_configFirmwareButton = NULL;
    ui_configFirmwareImage = NULL;
    ui_configFirmwareLabel = NULL;
    ui_configBackButton = NULL;
    ui_configBackImage = NULL;

}
