// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: sql-coffee-candy

#ifndef UI_CONFIGSCREEN_H
#define UI_CONFIGSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_configScreen
extern void ui_configScreen_screen_init(void);
extern void ui_configScreen_screen_destroy(void);
extern void ui_event_configScreen(lv_event_t * e);
extern lv_obj_t * ui_configScreen;
extern lv_obj_t * ui_configLabel;
extern void ui_event_configWifiButton(lv_event_t * e);
extern lv_obj_t * ui_configWifiButton;
extern lv_obj_t * ui_configWifiImage;
extern lv_obj_t * ui_configWifiLabel;
extern void ui_event_configSeverButton(lv_event_t * e);
extern lv_obj_t * ui_configSeverButton;
extern lv_obj_t * ui_configServerImage;
extern lv_obj_t * ui_configServerLabel;
extern void ui_event_configFirmwareButton(lv_event_t * e);
extern lv_obj_t * ui_configFirmwareButton;
extern lv_obj_t * ui_configFirmwareImage;
extern lv_obj_t * ui_configFirmwareLabel;
extern void ui_event_configBackButton(lv_event_t * e);
extern lv_obj_t * ui_configBackButton;
extern lv_obj_t * ui_configBackImage;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

