// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: sql-coffee-candy

#ifndef UI_DROPSCREEN_H
#define UI_DROPSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_dropScreen
extern void ui_dropScreen_screen_init(void);
extern void ui_dropScreen_screen_destroy(void);
extern void ui_event_dropScreen(lv_event_t * e);
extern lv_obj_t * ui_dropScreen;
extern lv_obj_t * ui_dropImage;
extern lv_obj_t * ui_dropProcessingLabel;
extern void ui_event_dropBackButton(lv_event_t * e);
extern lv_obj_t * ui_dropBackButton;
extern lv_obj_t * ui_dropBackImage;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

