// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: sql-coffee-candy

#include "ui.h"

lv_obj_t * ui_debugScreen = NULL;
lv_obj_t * ui_debugLabel = NULL;
lv_obj_t * ui_debugTextArea = NULL;
lv_obj_t * ui_debugCmdContainer = NULL;
lv_obj_t * ui_debugCmdLabel = NULL;
lv_obj_t * ui_debugCmdTextArea = NULL;
lv_obj_t * ui_debugFunction1Button = NULL;
lv_obj_t * ui_debugFunction1Label = NULL;
lv_obj_t * ui_debugFunction2Button = NULL;
lv_obj_t * ui_wifiConnectLabel3 = NULL;
lv_obj_t * ui_debugBackButton = NULL;
lv_obj_t * ui_debugBackImage = NULL;
lv_obj_t * ui_debugKeyboard = NULL;
// event funtions
void ui_event_debugScreen(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOAD_START) {
        debug_screen_load(e);
    }
    if(event_code == LV_EVENT_SCREEN_UNLOADED) {
        debug_screen_unload(e);
    }
}

void ui_event_debugCmdTextArea(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_FOCUSED) {
        keyboardUpAnimation_Animation(ui_debugKeyboard, 0);
        _ui_keyboard_set_target(ui_debugKeyboard,  ui_debugCmdTextArea);
    }
    if(event_code == LV_EVENT_DEFOCUSED) {
        keyboardDownAnimation_Animation(ui_debugKeyboard, 0);
    }
}

void ui_event_debugFunction1Button(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_RELEASED) {
        debug_function1(e);
    }
}

void ui_event_debugFunction2Button(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_RELEASED) {
        debug_function2(e);
    }
}

void ui_event_debugBackButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_RELEASED) {
        _ui_screen_change(&ui_firmwareScreen, LV_SCR_LOAD_ANIM_OVER_BOTTOM, 500, 0, &ui_firmwareScreen_screen_init);
        _ui_screen_delete(&ui_debugScreen);
    }
}

// build funtions

void ui_debugScreen_screen_init(void)
{
    ui_debugScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_debugScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_debugLabel = lv_label_create(ui_debugScreen);
    lv_obj_set_width(ui_debugLabel, 380);
    lv_obj_set_height(ui_debugLabel, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(ui_debugLabel, -200);
    lv_obj_set_y(ui_debugLabel, -205);
    lv_obj_set_align(ui_debugLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_debugLabel, "Debug");
    lv_obj_set_style_text_align(ui_debugLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_debugLabel, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_debugTextArea = lv_textarea_create(ui_debugScreen);
    lv_obj_set_width(ui_debugTextArea, 380);
    lv_obj_set_height(ui_debugTextArea, 400);
    lv_obj_set_x(ui_debugTextArea, -200);
    lv_obj_set_y(ui_debugTextArea, 30);
    lv_obj_set_align(ui_debugTextArea, LV_ALIGN_CENTER);

    ui_debugCmdContainer = lv_obj_create(ui_debugScreen);
    lv_obj_remove_style_all(ui_debugCmdContainer);
    lv_obj_set_width(ui_debugCmdContainer, 380);
    lv_obj_set_height(ui_debugCmdContainer, 50);
    lv_obj_set_x(ui_debugCmdContainer, 195);
    lv_obj_set_y(ui_debugCmdContainer, -155);
    lv_obj_set_align(ui_debugCmdContainer, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_debugCmdContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_debugCmdLabel = lv_label_create(ui_debugCmdContainer);
    lv_obj_set_width(ui_debugCmdLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_debugCmdLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_debugCmdLabel, -150);
    lv_obj_set_y(ui_debugCmdLabel, 0);
    lv_obj_set_align(ui_debugCmdLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_debugCmdLabel, "CMD");
    lv_obj_set_style_text_font(ui_debugCmdLabel, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_debugCmdTextArea = lv_textarea_create(ui_debugCmdContainer);
    lv_obj_set_width(ui_debugCmdTextArea, 300);
    lv_obj_set_height(ui_debugCmdTextArea, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(ui_debugCmdTextArea, 40);
    lv_obj_set_y(ui_debugCmdTextArea, 0);
    lv_obj_set_align(ui_debugCmdTextArea, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_debugCmdTextArea, "CMD");
    lv_textarea_set_one_line(ui_debugCmdTextArea, true);

    ui_debugFunction1Button = lv_btn_create(ui_debugScreen);
    lv_obj_set_width(ui_debugFunction1Button, 300);
    lv_obj_set_height(ui_debugFunction1Button, 70);
    lv_obj_set_x(ui_debugFunction1Button, 195);
    lv_obj_set_y(ui_debugFunction1Button, -25);
    lv_obj_set_align(ui_debugFunction1Button, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_debugFunction1Button, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_debugFunction1Button, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_debugFunction1Button, lv_color_hex(0xE8E8E8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_debugFunction1Button, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_debugFunction1Button, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_debugFunction1Button, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_debugFunction1Button, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_debugFunction1Button, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_debugFunction1Label = lv_label_create(ui_debugFunction1Button);
    lv_obj_set_width(ui_debugFunction1Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_debugFunction1Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_debugFunction1Label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_debugFunction1Label, "FUNCTION 1");
    lv_obj_set_style_text_color(ui_debugFunction1Label, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_debugFunction1Label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_debugFunction1Label, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_debugFunction2Button = lv_btn_create(ui_debugScreen);
    lv_obj_set_width(ui_debugFunction2Button, 300);
    lv_obj_set_height(ui_debugFunction2Button, 70);
    lv_obj_set_x(ui_debugFunction2Button, 195);
    lv_obj_set_y(ui_debugFunction2Button, 75);
    lv_obj_set_align(ui_debugFunction2Button, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_debugFunction2Button, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_debugFunction2Button, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_debugFunction2Button, lv_color_hex(0xE8E8E8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_debugFunction2Button, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_debugFunction2Button, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_debugFunction2Button, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_debugFunction2Button, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_debugFunction2Button, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_wifiConnectLabel3 = lv_label_create(ui_debugFunction2Button);
    lv_obj_set_width(ui_wifiConnectLabel3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_wifiConnectLabel3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_wifiConnectLabel3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_wifiConnectLabel3, "FUNCTION 2");
    lv_obj_set_style_text_color(ui_wifiConnectLabel3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_wifiConnectLabel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_wifiConnectLabel3, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_debugBackButton = lv_btn_create(ui_debugScreen);
    lv_obj_set_width(ui_debugBackButton, 60);
    lv_obj_set_height(ui_debugBackButton, 60);
    lv_obj_set_x(ui_debugBackButton, 360);
    lv_obj_set_y(ui_debugBackButton, 200);
    lv_obj_set_align(ui_debugBackButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_debugBackButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_debugBackButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_debugBackButton, lv_color_hex(0xE8E8E8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_debugBackButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_debugBackButton, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_debugBackButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_debugBackButton, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_debugBackButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_debugBackImage = lv_img_create(ui_debugBackButton);
    lv_obj_set_width(ui_debugBackImage, 50);
    lv_obj_set_height(ui_debugBackImage, 50);
    lv_obj_set_align(ui_debugBackImage, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_debugBackImage, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_debugBackImage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_debugKeyboard = lv_keyboard_create(ui_debugScreen);
    lv_obj_set_width(ui_debugKeyboard, 800);
    lv_obj_set_height(ui_debugKeyboard, 240);
    lv_obj_set_x(ui_debugKeyboard, 0);
    lv_obj_set_y(ui_debugKeyboard, 360);
    lv_obj_set_align(ui_debugKeyboard, LV_ALIGN_CENTER);

    lv_obj_add_event_cb(ui_debugCmdTextArea, ui_event_debugCmdTextArea, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_debugFunction1Button, ui_event_debugFunction1Button, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_debugFunction2Button, ui_event_debugFunction2Button, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_debugBackButton, ui_event_debugBackButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_debugScreen, ui_event_debugScreen, LV_EVENT_ALL, NULL);

}

void ui_debugScreen_screen_destroy(void)
{
    if(ui_debugScreen) lv_obj_del(ui_debugScreen);

    // NULL screen variables
    ui_debugScreen = NULL;
    ui_debugLabel = NULL;
    ui_debugTextArea = NULL;
    ui_debugCmdContainer = NULL;
    ui_debugCmdLabel = NULL;
    ui_debugCmdTextArea = NULL;
    ui_debugFunction1Button = NULL;
    ui_debugFunction1Label = NULL;
    ui_debugFunction2Button = NULL;
    ui_wifiConnectLabel3 = NULL;
    ui_debugBackButton = NULL;
    ui_debugBackImage = NULL;
    ui_debugKeyboard = NULL;

}
