// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: sql-coffee-candy

#ifndef UI_DROPDONESCREEN_H
#define UI_DROPDONESCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_dropDoneScreen
extern void ui_dropDoneScreen_screen_init(void);
extern void ui_dropDoneScreen_screen_destroy(void);
extern void ui_event_dropDoneScreen(lv_event_t * e);
extern lv_obj_t * ui_dropDoneScreen;
extern lv_obj_t * ui_dropDoneImage;
extern lv_obj_t * ui_dropDoneLabel;
extern void ui_event_dropDoneBackButton(lv_event_t * e);
extern lv_obj_t * ui_dropDoneBackButton;
extern lv_obj_t * ui_dropDoneBackLabel;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

