// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: sql-coffee-candy

#include "ui.h"

lv_obj_t * ui_dropDoneScreen = NULL;
lv_obj_t * ui_dropDoneImage = NULL;
lv_obj_t * ui_dropDoneLabel = NULL;
lv_obj_t * ui_dropDoneBackButton = NULL;
lv_obj_t * ui_dropDoneBackLabel = NULL;
// event funtions
void ui_event_dropDoneScreen(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOAD_START) {
        dropDone_screen_load(e);
    }
}

void ui_event_dropDoneBackButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_RELEASED) {
        _ui_screen_change(&ui_mainScreen, LV_SCR_LOAD_ANIM_OVER_BOTTOM, 500, 0, &ui_mainScreen_screen_init);
        _ui_screen_delete(&ui_dropDoneScreen);
    }
}

// build funtions

void ui_dropDoneScreen_screen_init(void)
{
    ui_dropDoneScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_dropDoneScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_dropDoneImage = lv_img_create(ui_dropDoneScreen);
    lv_obj_set_width(ui_dropDoneImage, 100);
    lv_obj_set_height(ui_dropDoneImage, 100);
    lv_obj_set_x(ui_dropDoneImage, 0);
    lv_obj_set_y(ui_dropDoneImage, -130);
    lv_obj_set_align(ui_dropDoneImage, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_dropDoneImage, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_dropDoneImage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_dropDoneLabel = lv_label_create(ui_dropDoneScreen);
    lv_obj_set_height(ui_dropDoneLabel, 50);
    lv_obj_set_width(ui_dropDoneLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_dropDoneLabel, 0);
    lv_obj_set_y(ui_dropDoneLabel, -5);
    lv_obj_set_align(ui_dropDoneLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_dropDoneLabel, "Done!");
    lv_obj_set_style_text_font(ui_dropDoneLabel, &lv_font_montserrat_42, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dropDoneBackButton = lv_btn_create(ui_dropDoneScreen);
    lv_obj_set_width(ui_dropDoneBackButton, 150);
    lv_obj_set_height(ui_dropDoneBackButton, 80);
    lv_obj_set_x(ui_dropDoneBackButton, 0);
    lv_obj_set_y(ui_dropDoneBackButton, 160);
    lv_obj_set_align(ui_dropDoneBackButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_dropDoneBackButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_dropDoneBackButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_dropDoneBackButton, lv_color_hex(0xE8E8E8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_dropDoneBackButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_dropDoneBackButton, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_dropDoneBackButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_dropDoneBackButton, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_dropDoneBackButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dropDoneBackLabel = lv_label_create(ui_dropDoneBackButton);
    lv_obj_set_height(ui_dropDoneBackLabel, 28);
    lv_obj_set_width(ui_dropDoneBackLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_align(ui_dropDoneBackLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_dropDoneBackLabel, "GO TITLE");
    lv_obj_set_style_text_color(ui_dropDoneBackLabel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_dropDoneBackLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_dropDoneBackLabel, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_dropDoneBackButton, ui_event_dropDoneBackButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_dropDoneScreen, ui_event_dropDoneScreen, LV_EVENT_ALL, NULL);

}

void ui_dropDoneScreen_screen_destroy(void)
{
    if(ui_dropDoneScreen) lv_obj_del(ui_dropDoneScreen);

    // NULL screen variables
    ui_dropDoneScreen = NULL;
    ui_dropDoneImage = NULL;
    ui_dropDoneLabel = NULL;
    ui_dropDoneBackButton = NULL;
    ui_dropDoneBackLabel = NULL;

}
