// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: sql-coffee-candy

#ifndef UI_DEBUGSCREEN_H
#define UI_DEBUGSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_debugScreen
extern void ui_debugScreen_screen_init(void);
extern void ui_debugScreen_screen_destroy(void);
extern void ui_event_debugScreen(lv_event_t * e);
extern lv_obj_t * ui_debugScreen;
extern lv_obj_t * ui_debugLabel;
extern lv_obj_t * ui_debugTextArea;
extern lv_obj_t * ui_debugCmdContainer;
extern lv_obj_t * ui_debugCmdLabel;
extern void ui_event_debugCmdTextArea(lv_event_t * e);
extern lv_obj_t * ui_debugCmdTextArea;
extern void ui_event_debugFunction1Button(lv_event_t * e);
extern lv_obj_t * ui_debugFunction1Button;
extern lv_obj_t * ui_debugFunction1Label;
extern void ui_event_debugFunction2Button(lv_event_t * e);
extern lv_obj_t * ui_debugFunction2Button;
extern lv_obj_t * ui_wifiConnectLabel3;
extern void ui_event_debugBackButton(lv_event_t * e);
extern lv_obj_t * ui_debugBackButton;
extern lv_obj_t * ui_debugBackImage;
extern lv_obj_t * ui_debugKeyboard;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

