// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: sql-coffee-candy

#include "ui.h"

lv_obj_t * ui_dropScreen = NULL;
lv_obj_t * ui_dropImage = NULL;
lv_obj_t * ui_dropProcessingLabel = NULL;
lv_obj_t * ui_dropBackButton = NULL;
lv_obj_t * ui_dropBackImage = NULL;
// event funtions
void ui_event_dropScreen(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOAD_START) {
        drop_screen_load(e);
    }
}

void ui_event_dropBackButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_RELEASED) {
        _ui_screen_change(&ui_flavorScreen, LV_SCR_LOAD_ANIM_OVER_BOTTOM, 500, 0, &ui_flavorScreen_screen_init);
        _ui_screen_delete(&ui_dropScreen);
    }
}

// build funtions

void ui_dropScreen_screen_init(void)
{
    ui_dropScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_dropScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_dropImage = lv_img_create(ui_dropScreen);
    lv_obj_set_width(ui_dropImage, 100);
    lv_obj_set_height(ui_dropImage, 100);
    lv_obj_set_x(ui_dropImage, 0);
    lv_obj_set_y(ui_dropImage, -130);
    lv_obj_set_align(ui_dropImage, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_dropImage, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_dropImage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_dropProcessingLabel = lv_label_create(ui_dropScreen);
    lv_obj_set_height(ui_dropProcessingLabel, 50);
    lv_obj_set_width(ui_dropProcessingLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_dropProcessingLabel, 0);
    lv_obj_set_y(ui_dropProcessingLabel, -5);
    lv_obj_set_align(ui_dropProcessingLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_dropProcessingLabel, "Processing...");
    lv_obj_set_style_text_font(ui_dropProcessingLabel, &lv_font_montserrat_42, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dropBackButton = lv_btn_create(ui_dropScreen);
    lv_obj_set_width(ui_dropBackButton, 60);
    lv_obj_set_height(ui_dropBackButton, 60);
    lv_obj_set_x(ui_dropBackButton, 360);
    lv_obj_set_y(ui_dropBackButton, 200);
    lv_obj_set_align(ui_dropBackButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_dropBackButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_dropBackButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_dropBackButton, lv_color_hex(0xE8E8E8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_dropBackButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_dropBackButton, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_dropBackButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_dropBackButton, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_dropBackButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dropBackImage = lv_img_create(ui_dropBackButton);
    lv_obj_set_width(ui_dropBackImage, 50);
    lv_obj_set_height(ui_dropBackImage, 50);
    lv_obj_set_align(ui_dropBackImage, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_dropBackImage, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_dropBackImage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_dropBackButton, ui_event_dropBackButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_dropScreen, ui_event_dropScreen, LV_EVENT_ALL, NULL);

}

void ui_dropScreen_screen_destroy(void)
{
    if(ui_dropScreen) lv_obj_del(ui_dropScreen);

    // NULL screen variables
    ui_dropScreen = NULL;
    ui_dropImage = NULL;
    ui_dropProcessingLabel = NULL;
    ui_dropBackButton = NULL;
    ui_dropBackImage = NULL;

}
