// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: sql-coffee-candy

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void main_screen_load(lv_event_t * e);
void main_screen_unload(lv_event_t * e);
void flavor_screen_load(lv_event_t * e);
void flavor_drop_strawberry(lv_event_t * e);
void flavor_drop_green_grapes(lv_event_t * e);
void flavor_drop_plum(lv_event_t * e);
void config_screen_load(lv_event_t * e);
void drop_screen_load(lv_event_t * e);
void dropDone_screen_load(lv_event_t * e);
void wifi_screen_load(lv_event_t * e);
void wifi_screen_unload(lv_event_t * e);
void wifi_connect(lv_event_t * e);
void wifi_restore(lv_event_t * e);
void server_screen_load(lv_event_t * e);
void server_screen_unload(lv_event_t * e);
void server_set(lv_event_t * e);
void firmware_screen_load(lv_event_t * e);
void firmware_check(lv_event_t * e);
void debug_screen_load(lv_event_t * e);
void debug_screen_unload(lv_event_t * e);
void debug_function1(lv_event_t * e);
void debug_function2(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
