// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: sql-coffee-candy

#include "ui.h"

lv_obj_t * ui_firmwareScreen = NULL;
lv_obj_t * ui_firmwareCurrentLabel = NULL;
lv_obj_t * ui_firmwareLatestLabel = NULL;
lv_obj_t * ui_firmwareCheckLabel = NULL;
lv_obj_t * ui_firmwareCheckButton = NULL;
lv_obj_t * ui_firmwareCheckNewLabel = NULL;
lv_obj_t * ui_firmwareDebugButton = NULL;
lv_obj_t * ui_firmwareDebugImage = NULL;
lv_obj_t * ui_firmwareBackButton = NULL;
lv_obj_t * ui_firmwareBackImage = NULL;
// event funtions
void ui_event_firmwareScreen(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOAD_START) {
        firmware_screen_load(e);
    }
}

void ui_event_firmwareCheckButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_RELEASED) {
        firmware_check(e);
    }
}

void ui_event_firmwareDebugButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_RELEASED) {
        _ui_screen_change(&ui_debugScreen, LV_SCR_LOAD_ANIM_OVER_BOTTOM, 500, 0, &ui_debugScreen_screen_init);
        _ui_screen_delete(&ui_firmwareScreen);
    }
}

void ui_event_firmwareBackButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_RELEASED) {
        _ui_screen_change(&ui_configScreen, LV_SCR_LOAD_ANIM_OVER_BOTTOM, 500, 0, &ui_configScreen_screen_init);
        _ui_screen_delete(&ui_firmwareScreen);
    }
}

// build funtions

void ui_firmwareScreen_screen_init(void)
{
    ui_firmwareScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_firmwareScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_firmwareCurrentLabel = lv_label_create(ui_firmwareScreen);
    lv_obj_set_width(ui_firmwareCurrentLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_firmwareCurrentLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_firmwareCurrentLabel, 0);
    lv_obj_set_y(ui_firmwareCurrentLabel, -99);
    lv_obj_set_align(ui_firmwareCurrentLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_firmwareCurrentLabel, "Current Version Loading...");
    lv_obj_set_style_text_font(ui_firmwareCurrentLabel, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_firmwareLatestLabel = lv_label_create(ui_firmwareScreen);
    lv_obj_set_width(ui_firmwareLatestLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_firmwareLatestLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_firmwareLatestLabel, 0);
    lv_obj_set_y(ui_firmwareLatestLabel, -47);
    lv_obj_set_align(ui_firmwareLatestLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_firmwareLatestLabel, "Latest Version Loading...");
    lv_obj_set_style_text_font(ui_firmwareLatestLabel, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_firmwareCheckLabel = lv_label_create(ui_firmwareScreen);
    lv_obj_set_width(ui_firmwareCheckLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_firmwareCheckLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_firmwareCheckLabel, 0);
    lv_obj_set_y(ui_firmwareCheckLabel, 65);
    lv_obj_set_align(ui_firmwareCheckLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_firmwareCheckLabel, "No new firmware version found");
    lv_obj_set_style_text_font(ui_firmwareCheckLabel, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_firmwareCheckButton = lv_btn_create(ui_firmwareScreen);
    lv_obj_set_width(ui_firmwareCheckButton, 200);
    lv_obj_set_height(ui_firmwareCheckButton, 50);
    lv_obj_set_x(ui_firmwareCheckButton, 0);
    lv_obj_set_y(ui_firmwareCheckButton, 120);
    lv_obj_set_align(ui_firmwareCheckButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_firmwareCheckButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_firmwareCheckButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_firmwareCheckButton, lv_color_hex(0xE8E8E8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_firmwareCheckButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_firmwareCheckButton, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_firmwareCheckButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_firmwareCheckButton, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_firmwareCheckButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_firmwareCheckNewLabel = lv_label_create(ui_firmwareCheckButton);
    lv_obj_set_width(ui_firmwareCheckNewLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_firmwareCheckNewLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_firmwareCheckNewLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_firmwareCheckNewLabel, "Check for latest version");
    lv_obj_set_style_text_color(ui_firmwareCheckNewLabel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_firmwareCheckNewLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_firmwareDebugButton = lv_btn_create(ui_firmwareScreen);
    lv_obj_set_width(ui_firmwareDebugButton, 60);
    lv_obj_set_height(ui_firmwareDebugButton, 60);
    lv_obj_set_x(ui_firmwareDebugButton, -360);
    lv_obj_set_y(ui_firmwareDebugButton, 200);
    lv_obj_set_align(ui_firmwareDebugButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_firmwareDebugButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_firmwareDebugButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_firmwareDebugButton, lv_color_hex(0xE8E8E8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_firmwareDebugButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_firmwareDebugButton, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_firmwareDebugButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_firmwareDebugButton, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_firmwareDebugButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_firmwareDebugImage = lv_img_create(ui_firmwareDebugButton);
    lv_obj_set_width(ui_firmwareDebugImage, 50);
    lv_obj_set_height(ui_firmwareDebugImage, 50);
    lv_obj_set_align(ui_firmwareDebugImage, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_firmwareDebugImage, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_firmwareDebugImage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_firmwareBackButton = lv_btn_create(ui_firmwareScreen);
    lv_obj_set_width(ui_firmwareBackButton, 60);
    lv_obj_set_height(ui_firmwareBackButton, 60);
    lv_obj_set_x(ui_firmwareBackButton, 360);
    lv_obj_set_y(ui_firmwareBackButton, 200);
    lv_obj_set_align(ui_firmwareBackButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_firmwareBackButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_firmwareBackButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_firmwareBackButton, lv_color_hex(0xE8E8E8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_firmwareBackButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_firmwareBackButton, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_firmwareBackButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_firmwareBackButton, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_firmwareBackButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_firmwareBackImage = lv_img_create(ui_firmwareBackButton);
    lv_obj_set_width(ui_firmwareBackImage, 50);
    lv_obj_set_height(ui_firmwareBackImage, 50);
    lv_obj_set_align(ui_firmwareBackImage, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_firmwareBackImage, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_firmwareBackImage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_firmwareCheckButton, ui_event_firmwareCheckButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_firmwareDebugButton, ui_event_firmwareDebugButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_firmwareBackButton, ui_event_firmwareBackButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_firmwareScreen, ui_event_firmwareScreen, LV_EVENT_ALL, NULL);

}

void ui_firmwareScreen_screen_destroy(void)
{
    if(ui_firmwareScreen) lv_obj_del(ui_firmwareScreen);

    // NULL screen variables
    ui_firmwareScreen = NULL;
    ui_firmwareCurrentLabel = NULL;
    ui_firmwareLatestLabel = NULL;
    ui_firmwareCheckLabel = NULL;
    ui_firmwareCheckButton = NULL;
    ui_firmwareCheckNewLabel = NULL;
    ui_firmwareDebugButton = NULL;
    ui_firmwareDebugImage = NULL;
    ui_firmwareBackButton = NULL;
    ui_firmwareBackImage = NULL;

}
