// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: sql-coffee-candy

#include "ui.h"

lv_obj_t * ui_flavorScreen = NULL;
lv_obj_t * ui_flavorLable = NULL;
lv_obj_t * ui_flavorStrawberryButton = NULL;
lv_obj_t * ui_flavorStrawberryImage = NULL;
lv_obj_t * ui_flavorStrawberryLabel = NULL;
lv_obj_t * ui_flavorGreenGrapesButton = NULL;
lv_obj_t * ui_flavorGreenGrapesImage = NULL;
lv_obj_t * ui_flavorGreenGrapesLabel = NULL;
lv_obj_t * ui_flavorPlumButton = NULL;
lv_obj_t * ui_flavorPlumImage = NULL;
lv_obj_t * ui_flavorPlumLabel = NULL;
lv_obj_t * ui_flavorBackButton = NULL;
lv_obj_t * ui_flavorBackImage = NULL;
// event funtions
void ui_event_flavorScreen(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOAD_START) {
        flavor_screen_load(e);
    }
}

void ui_event_flavorStrawberryButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_RELEASED) {
        _ui_screen_change(&ui_dropScreen, LV_SCR_LOAD_ANIM_OVER_BOTTOM, 500, 0, &ui_dropScreen_screen_init);
        _ui_screen_delete(&ui_flavorScreen);
        flavor_drop_strawberry(e);
    }
}

void ui_event_flavorGreenGrapesButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_RELEASED) {
        _ui_screen_change(&ui_dropScreen, LV_SCR_LOAD_ANIM_OVER_BOTTOM, 500, 0, &ui_dropScreen_screen_init);
        _ui_screen_delete(&ui_flavorScreen);
        flavor_drop_green_grapes(e);
    }
}

void ui_event_flavorPlumButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_RELEASED) {
        _ui_screen_change(&ui_dropScreen, LV_SCR_LOAD_ANIM_OVER_BOTTOM, 500, 0, &ui_dropScreen_screen_init);
        _ui_screen_delete(&ui_flavorScreen);
        flavor_drop_plum(e);
    }
}

void ui_event_flavorBackButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_RELEASED) {
        _ui_screen_change(&ui_mainScreen, LV_SCR_LOAD_ANIM_OVER_BOTTOM, 500, 0, &ui_mainScreen_screen_init);
        _ui_screen_delete(&ui_flavorScreen);
    }
}

// build funtions

void ui_flavorScreen_screen_init(void)
{
    ui_flavorScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_flavorScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_flavorLable = lv_label_create(ui_flavorScreen);
    lv_obj_set_height(ui_flavorLable, 42);
    lv_obj_set_width(ui_flavorLable, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_flavorLable, 0);
    lv_obj_set_y(ui_flavorLable, -140);
    lv_obj_set_align(ui_flavorLable, LV_ALIGN_CENTER);
    lv_label_set_text(ui_flavorLable, "Flavor");
    lv_obj_set_style_text_font(ui_flavorLable, &lv_font_montserrat_42, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_flavorStrawberryButton = lv_btn_create(ui_flavorScreen);
    lv_obj_set_width(ui_flavorStrawberryButton, 200);
    lv_obj_set_height(ui_flavorStrawberryButton, 200);
    lv_obj_set_x(ui_flavorStrawberryButton, -250);
    lv_obj_set_y(ui_flavorStrawberryButton, 40);
    lv_obj_set_align(ui_flavorStrawberryButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_flavorStrawberryButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_flavorStrawberryButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_flavorStrawberryButton, lv_color_hex(0xE8E8E8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_flavorStrawberryButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_flavorStrawberryButton, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_flavorStrawberryButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_flavorStrawberryButton, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_flavorStrawberryButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_flavorStrawberryImage = lv_img_create(ui_flavorStrawberryButton);
    lv_obj_set_width(ui_flavorStrawberryImage, 100);
    lv_obj_set_height(ui_flavorStrawberryImage, 100);
    lv_obj_set_x(ui_flavorStrawberryImage, 0);
    lv_obj_set_y(ui_flavorStrawberryImage, -33);
    lv_obj_set_align(ui_flavorStrawberryImage, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_flavorStrawberryImage, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_flavorStrawberryImage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_flavorStrawberryLabel = lv_label_create(ui_flavorStrawberryButton);
    lv_obj_set_height(ui_flavorStrawberryLabel, 56);
    lv_obj_set_width(ui_flavorStrawberryLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_flavorStrawberryLabel, 0);
    lv_obj_set_y(ui_flavorStrawberryLabel, 55);
    lv_obj_set_align(ui_flavorStrawberryLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_flavorStrawberryLabel, "STRAW\nBERRY");
    lv_obj_set_style_text_color(ui_flavorStrawberryLabel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_flavorStrawberryLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_flavorStrawberryLabel, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_flavorGreenGrapesButton = lv_btn_create(ui_flavorScreen);
    lv_obj_set_width(ui_flavorGreenGrapesButton, 200);
    lv_obj_set_height(ui_flavorGreenGrapesButton, 200);
    lv_obj_set_x(ui_flavorGreenGrapesButton, 0);
    lv_obj_set_y(ui_flavorGreenGrapesButton, 40);
    lv_obj_set_align(ui_flavorGreenGrapesButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_flavorGreenGrapesButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_flavorGreenGrapesButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_flavorGreenGrapesButton, lv_color_hex(0xE8E8E8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_flavorGreenGrapesButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_flavorGreenGrapesButton, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_flavorGreenGrapesButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_flavorGreenGrapesButton, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_flavorGreenGrapesButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_flavorGreenGrapesImage = lv_img_create(ui_flavorGreenGrapesButton);
    lv_obj_set_width(ui_flavorGreenGrapesImage, 100);
    lv_obj_set_height(ui_flavorGreenGrapesImage, 100);
    lv_obj_set_x(ui_flavorGreenGrapesImage, 0);
    lv_obj_set_y(ui_flavorGreenGrapesImage, -33);
    lv_obj_set_align(ui_flavorGreenGrapesImage, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_flavorGreenGrapesImage, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_flavorGreenGrapesImage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_flavorGreenGrapesLabel = lv_label_create(ui_flavorGreenGrapesButton);
    lv_obj_set_height(ui_flavorGreenGrapesLabel, 56);
    lv_obj_set_width(ui_flavorGreenGrapesLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_flavorGreenGrapesLabel, 0);
    lv_obj_set_y(ui_flavorGreenGrapesLabel, 55);
    lv_obj_set_align(ui_flavorGreenGrapesLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_flavorGreenGrapesLabel, "GREEN\nGRAPES\n");
    lv_obj_set_style_text_color(ui_flavorGreenGrapesLabel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_flavorGreenGrapesLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_flavorGreenGrapesLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_flavorGreenGrapesLabel, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_flavorPlumButton = lv_btn_create(ui_flavorScreen);
    lv_obj_set_width(ui_flavorPlumButton, 200);
    lv_obj_set_height(ui_flavorPlumButton, 200);
    lv_obj_set_x(ui_flavorPlumButton, 250);
    lv_obj_set_y(ui_flavorPlumButton, 40);
    lv_obj_set_align(ui_flavorPlumButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_flavorPlumButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_flavorPlumButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_flavorPlumButton, lv_color_hex(0xE8E8E8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_flavorPlumButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_flavorPlumButton, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_flavorPlumButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_flavorPlumButton, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_flavorPlumButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_flavorPlumImage = lv_img_create(ui_flavorPlumButton);
    lv_obj_set_width(ui_flavorPlumImage, 100);
    lv_obj_set_height(ui_flavorPlumImage, 100);
    lv_obj_set_x(ui_flavorPlumImage, 0);
    lv_obj_set_y(ui_flavorPlumImage, -19);
    lv_obj_set_align(ui_flavorPlumImage, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_flavorPlumImage, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_flavorPlumImage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_flavorPlumLabel = lv_label_create(ui_flavorPlumButton);
    lv_obj_set_height(ui_flavorPlumLabel, 28);
    lv_obj_set_width(ui_flavorPlumLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_flavorPlumLabel, 0);
    lv_obj_set_y(ui_flavorPlumLabel, 55);
    lv_obj_set_align(ui_flavorPlumLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_flavorPlumLabel, "PLUM");
    lv_obj_set_style_text_color(ui_flavorPlumLabel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_flavorPlumLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_flavorPlumLabel, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_flavorBackButton = lv_btn_create(ui_flavorScreen);
    lv_obj_set_width(ui_flavorBackButton, 60);
    lv_obj_set_height(ui_flavorBackButton, 60);
    lv_obj_set_x(ui_flavorBackButton, 360);
    lv_obj_set_y(ui_flavorBackButton, 200);
    lv_obj_set_align(ui_flavorBackButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_flavorBackButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_flavorBackButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_flavorBackButton, lv_color_hex(0xE8E8E8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_flavorBackButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_flavorBackButton, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_flavorBackButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_flavorBackButton, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_flavorBackButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_flavorBackImage = lv_img_create(ui_flavorBackButton);
    lv_obj_set_width(ui_flavorBackImage, 50);
    lv_obj_set_height(ui_flavorBackImage, 50);
    lv_obj_set_align(ui_flavorBackImage, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_flavorBackImage, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_flavorBackImage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_flavorStrawberryButton, ui_event_flavorStrawberryButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_flavorGreenGrapesButton, ui_event_flavorGreenGrapesButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_flavorPlumButton, ui_event_flavorPlumButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_flavorBackButton, ui_event_flavorBackButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_flavorScreen, ui_event_flavorScreen, LV_EVENT_ALL, NULL);

}

void ui_flavorScreen_screen_destroy(void)
{
    if(ui_flavorScreen) lv_obj_del(ui_flavorScreen);

    // NULL screen variables
    ui_flavorScreen = NULL;
    ui_flavorLable = NULL;
    ui_flavorStrawberryButton = NULL;
    ui_flavorStrawberryImage = NULL;
    ui_flavorStrawberryLabel = NULL;
    ui_flavorGreenGrapesButton = NULL;
    ui_flavorGreenGrapesImage = NULL;
    ui_flavorGreenGrapesLabel = NULL;
    ui_flavorPlumButton = NULL;
    ui_flavorPlumImage = NULL;
    ui_flavorPlumLabel = NULL;
    ui_flavorBackButton = NULL;
    ui_flavorBackImage = NULL;

}
