// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: sql-coffee-candy

#ifndef UI_FLAVORSCREEN_H
#define UI_FLAVORSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_flavorScreen
extern void ui_flavorScreen_screen_init(void);
extern void ui_flavorScreen_screen_destroy(void);
extern void ui_event_flavorScreen(lv_event_t * e);
extern lv_obj_t * ui_flavorScreen;
extern lv_obj_t * ui_flavorLable;
extern void ui_event_flavorStrawberryButton(lv_event_t * e);
extern lv_obj_t * ui_flavorStrawberryButton;
extern lv_obj_t * ui_flavorStrawberryImage;
extern lv_obj_t * ui_flavorStrawberryLabel;
extern void ui_event_flavorGreenGrapesButton(lv_event_t * e);
extern lv_obj_t * ui_flavorGreenGrapesButton;
extern lv_obj_t * ui_flavorGreenGrapesImage;
extern lv_obj_t * ui_flavorGreenGrapesLabel;
extern void ui_event_flavorPlumButton(lv_event_t * e);
extern lv_obj_t * ui_flavorPlumButton;
extern lv_obj_t * ui_flavorPlumImage;
extern lv_obj_t * ui_flavorPlumLabel;
extern void ui_event_flavorBackButton(lv_event_t * e);
extern lv_obj_t * ui_flavorBackButton;
extern lv_obj_t * ui_flavorBackImage;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

