// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: sql-coffee-candy

#ifndef UI_MAINSCREEN_H
#define UI_MAINSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_mainScreen
extern void ui_mainScreen_screen_init(void);
extern void ui_mainScreen_screen_destroy(void);
extern void ui_event_mainScreen(lv_event_t * e);
extern lv_obj_t * ui_mainScreen;
extern lv_obj_t * ui_mainLableContainer;
extern lv_obj_t * ui_mainFirmwareLabel;
extern lv_obj_t * ui_mainWiFiLabel;
extern void ui_event_mainConfigButton(lv_event_t * e);
extern lv_obj_t * ui_mainConfigButton;
extern lv_obj_t * ui_mainConfigImage;
extern lv_obj_t * ui_mainConfigLabel;
extern void ui_event_mainStartButton(lv_event_t * e);
extern lv_obj_t * ui_mainStartButton;
extern lv_obj_t * ui_mainStartImage;
extern lv_obj_t * ui_mainStartLabel;
extern lv_obj_t * ui_mainImage;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

