// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: sql-coffee-candy

#include "ui.h"

lv_obj_t * ui_mainScreen = NULL;
lv_obj_t * ui_mainLableContainer = NULL;
lv_obj_t * ui_mainFirmwareLabel = NULL;
lv_obj_t * ui_mainWiFiLabel = NULL;
lv_obj_t * ui_mainConfigButton = NULL;
lv_obj_t * ui_mainConfigImage = NULL;
lv_obj_t * ui_mainConfigLabel = NULL;
lv_obj_t * ui_mainStartButton = NULL;
lv_obj_t * ui_mainStartImage = NULL;
lv_obj_t * ui_mainStartLabel = NULL;
lv_obj_t * ui_mainImage = NULL;
// event funtions
void ui_event_mainScreen(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOAD_START) {
        main_screen_load(e);
    }
    if(event_code == LV_EVENT_SCREEN_UNLOADED) {
        main_screen_unload(e);
    }
}

void ui_event_mainConfigButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_RELEASED) {
        _ui_screen_change(&ui_configScreen, LV_SCR_LOAD_ANIM_OVER_BOTTOM, 500, 0, &ui_configScreen_screen_init);
        _ui_screen_delete(&ui_mainScreen);
    }
}

void ui_event_mainStartButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_RELEASED) {
        _ui_screen_change(&ui_flavorScreen, LV_SCR_LOAD_ANIM_OVER_BOTTOM, 500, 0, &ui_flavorScreen_screen_init);
        _ui_screen_delete(&ui_mainScreen);
    }
}

// build funtions

void ui_mainScreen_screen_init(void)
{
    ui_mainScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_mainScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_mainLableContainer = lv_obj_create(ui_mainScreen);
    lv_obj_remove_style_all(ui_mainLableContainer);
    lv_obj_set_width(ui_mainLableContainer, 180);
    lv_obj_set_height(ui_mainLableContainer, 110);
    lv_obj_set_x(ui_mainLableContainer, 300);
    lv_obj_set_y(ui_mainLableContainer, -175);
    lv_obj_set_align(ui_mainLableContainer, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_mainLableContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_mainFirmwareLabel = lv_label_create(ui_mainLableContainer);
    lv_obj_set_width(ui_mainFirmwareLabel, 180);
    lv_obj_set_height(ui_mainFirmwareLabel, 14);
    lv_obj_set_x(ui_mainFirmwareLabel, 0);
    lv_obj_set_y(ui_mainFirmwareLabel, -10);
    lv_obj_set_align(ui_mainFirmwareLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_mainFirmwareLabel, "Firmware Ver. Loading...");
    lv_obj_set_style_text_align(ui_mainFirmwareLabel, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_mainWiFiLabel = lv_label_create(ui_mainLableContainer);
    lv_obj_set_width(ui_mainWiFiLabel, 180);
    lv_obj_set_height(ui_mainWiFiLabel, 14);
    lv_obj_set_x(ui_mainWiFiLabel, 0);
    lv_obj_set_y(ui_mainWiFiLabel, 10);
    lv_obj_set_align(ui_mainWiFiLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_mainWiFiLabel, "Wi-Fi: Disconnected");
    lv_obj_set_style_text_align(ui_mainWiFiLabel, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_mainConfigButton = lv_btn_create(ui_mainScreen);
    lv_obj_set_width(ui_mainConfigButton, 180);
    lv_obj_set_height(ui_mainConfigButton, 110);
    lv_obj_set_x(ui_mainConfigButton, 300);
    lv_obj_set_y(ui_mainConfigButton, -55);
    lv_obj_set_align(ui_mainConfigButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_mainConfigButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_mainConfigButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_mainConfigButton, lv_color_hex(0xE8E8E8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_mainConfigButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_mainConfigButton, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_mainConfigButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_mainConfigButton, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_mainConfigButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_mainConfigImage = lv_img_create(ui_mainConfigButton);
    lv_obj_set_width(ui_mainConfigImage, 60);
    lv_obj_set_height(ui_mainConfigImage, 60);
    lv_obj_set_x(ui_mainConfigImage, 0);
    lv_obj_set_y(ui_mainConfigImage, -15);
    lv_obj_set_align(ui_mainConfigImage, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_mainConfigImage, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_mainConfigImage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_mainConfigLabel = lv_label_create(ui_mainConfigButton);
    lv_obj_set_height(ui_mainConfigLabel, 30);
    lv_obj_set_width(ui_mainConfigLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_mainConfigLabel, 0);
    lv_obj_set_y(ui_mainConfigLabel, 30);
    lv_obj_set_align(ui_mainConfigLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_mainConfigLabel, "CONFIG");
    lv_obj_set_style_text_color(ui_mainConfigLabel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_mainConfigLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_mainConfigLabel, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_mainStartButton = lv_btn_create(ui_mainScreen);
    lv_obj_set_width(ui_mainStartButton, 180);
    lv_obj_set_height(ui_mainStartButton, 220);
    lv_obj_set_x(ui_mainStartButton, 300);
    lv_obj_set_y(ui_mainStartButton, 120);
    lv_obj_set_align(ui_mainStartButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_mainStartButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_mainStartButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_mainStartButton, lv_color_hex(0xE8E8E8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_mainStartButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_mainStartButton, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_mainStartButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_mainStartButton, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_mainStartButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_mainStartImage = lv_img_create(ui_mainStartButton);
    lv_obj_set_width(ui_mainStartImage, 60);
    lv_obj_set_height(ui_mainStartImage, 60);
    lv_obj_set_x(ui_mainStartImage, 0);
    lv_obj_set_y(ui_mainStartImage, -15);
    lv_obj_set_align(ui_mainStartImage, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_mainStartImage, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_mainStartImage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_mainStartLabel = lv_label_create(ui_mainStartButton);
    lv_obj_set_height(ui_mainStartLabel, 30);
    lv_obj_set_width(ui_mainStartLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_mainStartLabel, 0);
    lv_obj_set_y(ui_mainStartLabel, 30);
    lv_obj_set_align(ui_mainStartLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_mainStartLabel, "START");
    lv_obj_set_style_text_color(ui_mainStartLabel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_mainStartLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_mainStartLabel, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_mainImage = lv_img_create(ui_mainScreen);
    lv_obj_set_width(ui_mainImage, 600);
    lv_obj_set_height(ui_mainImage, 480);
    lv_obj_set_x(ui_mainImage, -100);
    lv_obj_set_y(ui_mainImage, 0);
    lv_obj_set_align(ui_mainImage, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_mainImage, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_mainImage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_mainConfigButton, ui_event_mainConfigButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_mainStartButton, ui_event_mainStartButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_mainScreen, ui_event_mainScreen, LV_EVENT_ALL, NULL);

}

void ui_mainScreen_screen_destroy(void)
{
    if(ui_mainScreen) lv_obj_del(ui_mainScreen);

    // NULL screen variables
    ui_mainScreen = NULL;
    ui_mainLableContainer = NULL;
    ui_mainFirmwareLabel = NULL;
    ui_mainWiFiLabel = NULL;
    ui_mainConfigButton = NULL;
    ui_mainConfigImage = NULL;
    ui_mainConfigLabel = NULL;
    ui_mainStartButton = NULL;
    ui_mainStartImage = NULL;
    ui_mainStartLabel = NULL;
    ui_mainImage = NULL;

}
