// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: sql-coffee-candy

#ifndef UI_SERVERSCREEN_H
#define UI_SERVERSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_serverScreen
extern void ui_serverScreen_screen_init(void);
extern void ui_serverScreen_screen_destroy(void);
extern void ui_event_serverScreen(lv_event_t * e);
extern lv_obj_t * ui_serverScreen;
extern lv_obj_t * ui_serverLabel;
extern lv_obj_t * ui_serverTextArea;
extern lv_obj_t * ui_serverAddressContainer;
extern lv_obj_t * ui_serverAddressLabel;
extern void ui_event_serverAddressTextArea(lv_event_t * e);
extern lv_obj_t * ui_serverAddressTextArea;
extern lv_obj_t * ui_serverPwContainer;
extern lv_obj_t * ui_serverPwLabel;
extern void ui_event_serverPwTextArea(lv_event_t * e);
extern lv_obj_t * ui_serverPwTextArea;
extern void ui_event_serverSetButton(lv_event_t * e);
extern lv_obj_t * ui_serverSetButton;
extern lv_obj_t * ui_serverSetLabel;
extern void ui_event_serverBackButton(lv_event_t * e);
extern lv_obj_t * ui_serverBackButton;
extern lv_obj_t * ui_serverBackImage;
extern lv_obj_t * ui_serverKeyboard;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

