// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: sql-coffee-candy

#include "ui.h"

lv_obj_t * ui_serverScreen = NULL;
lv_obj_t * ui_serverLabel = NULL;
lv_obj_t * ui_serverTextArea = NULL;
lv_obj_t * ui_serverAddressContainer = NULL;
lv_obj_t * ui_serverAddressLabel = NULL;
lv_obj_t * ui_serverAddressTextArea = NULL;
lv_obj_t * ui_serverPwContainer = NULL;
lv_obj_t * ui_serverPwLabel = NULL;
lv_obj_t * ui_serverPwTextArea = NULL;
lv_obj_t * ui_serverSetButton = NULL;
lv_obj_t * ui_serverSetLabel = NULL;
lv_obj_t * ui_serverBackButton = NULL;
lv_obj_t * ui_serverBackImage = NULL;
lv_obj_t * ui_serverKeyboard = NULL;
// event funtions
void ui_event_serverScreen(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOAD_START) {
        server_screen_load(e);
    }
    if(event_code == LV_EVENT_SCREEN_UNLOADED) {
        server_screen_unload(e);
    }
}

void ui_event_serverAddressTextArea(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_FOCUSED) {
        keyboardUpAnimation_Animation(ui_serverKeyboard, 0);
        _ui_keyboard_set_target(ui_serverKeyboard,  ui_serverAddressTextArea);
    }
    if(event_code == LV_EVENT_DEFOCUSED) {
        keyboardDownAnimation_Animation(ui_serverKeyboard, 0);
    }
}

void ui_event_serverPwTextArea(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_FOCUSED) {
        keyboardUpAnimation_Animation(ui_serverKeyboard, 0);
        _ui_keyboard_set_target(ui_serverKeyboard,  ui_serverPwTextArea);
    }
    if(event_code == LV_EVENT_DEFOCUSED) {
        keyboardDownAnimation_Animation(ui_serverKeyboard, 0);
    }
}

void ui_event_serverSetButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_RELEASED) {
        server_set(e);
    }
}

void ui_event_serverBackButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_RELEASED) {
        _ui_screen_change(&ui_configScreen, LV_SCR_LOAD_ANIM_OVER_BOTTOM, 500, 0, &ui_configScreen_screen_init);
        _ui_screen_delete(&ui_serverScreen);
    }
}

// build funtions

void ui_serverScreen_screen_init(void)
{
    ui_serverScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_serverScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_serverLabel = lv_label_create(ui_serverScreen);
    lv_obj_set_width(ui_serverLabel, 380);
    lv_obj_set_height(ui_serverLabel, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(ui_serverLabel, -200);
    lv_obj_set_y(ui_serverLabel, -205);
    lv_obj_set_align(ui_serverLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_serverLabel, "Current Server: xxx.xxx.xxx.xxx:xxxx");
    lv_obj_set_style_text_align(ui_serverLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_serverTextArea = lv_textarea_create(ui_serverScreen);
    lv_obj_set_width(ui_serverTextArea, 380);
    lv_obj_set_height(ui_serverTextArea, 400);
    lv_obj_set_x(ui_serverTextArea, -200);
    lv_obj_set_y(ui_serverTextArea, 30);
    lv_obj_set_align(ui_serverTextArea, LV_ALIGN_CENTER);

    ui_serverAddressContainer = lv_obj_create(ui_serverScreen);
    lv_obj_remove_style_all(ui_serverAddressContainer);
    lv_obj_set_width(ui_serverAddressContainer, 380);
    lv_obj_set_height(ui_serverAddressContainer, 50);
    lv_obj_set_x(ui_serverAddressContainer, 195);
    lv_obj_set_y(ui_serverAddressContainer, -155);
    lv_obj_set_align(ui_serverAddressContainer, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_serverAddressContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_serverAddressLabel = lv_label_create(ui_serverAddressContainer);
    lv_obj_set_width(ui_serverAddressLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_serverAddressLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_serverAddressLabel, -130);
    lv_obj_set_y(ui_serverAddressLabel, 0);
    lv_obj_set_align(ui_serverAddressLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_serverAddressLabel, "SERVER");
    lv_obj_set_style_text_font(ui_serverAddressLabel, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_serverAddressTextArea = lv_textarea_create(ui_serverAddressContainer);
    lv_obj_set_width(ui_serverAddressTextArea, 250);
    lv_obj_set_height(ui_serverAddressTextArea, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(ui_serverAddressTextArea, 65);
    lv_obj_set_y(ui_serverAddressTextArea, -2);
    lv_obj_set_align(ui_serverAddressTextArea, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_serverAddressTextArea, "Server's Address");
    lv_textarea_set_one_line(ui_serverAddressTextArea, true);

    ui_serverPwContainer = lv_obj_create(ui_serverScreen);
    lv_obj_remove_style_all(ui_serverPwContainer);
    lv_obj_set_width(ui_serverPwContainer, 380);
    lv_obj_set_height(ui_serverPwContainer, 50);
    lv_obj_set_x(ui_serverPwContainer, 195);
    lv_obj_set_y(ui_serverPwContainer, -55);
    lv_obj_set_align(ui_serverPwContainer, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_serverPwContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_serverPwLabel = lv_label_create(ui_serverPwContainer);
    lv_obj_set_width(ui_serverPwLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_serverPwLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_serverPwLabel, -130);
    lv_obj_set_y(ui_serverPwLabel, 0);
    lv_obj_set_align(ui_serverPwLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_serverPwLabel, "PORT");
    lv_obj_set_style_text_font(ui_serverPwLabel, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_serverPwTextArea = lv_textarea_create(ui_serverPwContainer);
    lv_obj_set_width(ui_serverPwTextArea, 250);
    lv_obj_set_height(ui_serverPwTextArea, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(ui_serverPwTextArea, 60);
    lv_obj_set_y(ui_serverPwTextArea, 0);
    lv_obj_set_align(ui_serverPwTextArea, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_serverPwTextArea, "Server's Port");
    lv_textarea_set_one_line(ui_serverPwTextArea, true);
    lv_textarea_set_password_mode(ui_serverPwTextArea, true);

    ui_serverSetButton = lv_btn_create(ui_serverScreen);
    lv_obj_set_width(ui_serverSetButton, 300);
    lv_obj_set_height(ui_serverSetButton, 70);
    lv_obj_set_x(ui_serverSetButton, 195);
    lv_obj_set_y(ui_serverSetButton, 50);
    lv_obj_set_align(ui_serverSetButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_serverSetButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_serverSetButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_serverSetButton, lv_color_hex(0xE8E8E8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_serverSetButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_serverSetButton, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_serverSetButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_serverSetButton, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_serverSetButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_serverSetLabel = lv_label_create(ui_serverSetButton);
    lv_obj_set_width(ui_serverSetLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_serverSetLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_serverSetLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_serverSetLabel, "SET");
    lv_obj_set_style_text_color(ui_serverSetLabel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_serverSetLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_serverSetLabel, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_serverBackButton = lv_btn_create(ui_serverScreen);
    lv_obj_set_width(ui_serverBackButton, 60);
    lv_obj_set_height(ui_serverBackButton, 60);
    lv_obj_set_x(ui_serverBackButton, 360);
    lv_obj_set_y(ui_serverBackButton, 200);
    lv_obj_set_align(ui_serverBackButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_serverBackButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_serverBackButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_serverBackButton, lv_color_hex(0xE8E8E8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_serverBackButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_serverBackButton, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_serverBackButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_serverBackButton, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_serverBackButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_serverBackImage = lv_img_create(ui_serverBackButton);
    lv_obj_set_width(ui_serverBackImage, 50);
    lv_obj_set_height(ui_serverBackImage, 50);
    lv_obj_set_align(ui_serverBackImage, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_serverBackImage, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_serverBackImage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_serverKeyboard = lv_keyboard_create(ui_serverScreen);
    lv_obj_set_width(ui_serverKeyboard, 800);
    lv_obj_set_height(ui_serverKeyboard, 240);
    lv_obj_set_x(ui_serverKeyboard, 0);
    lv_obj_set_y(ui_serverKeyboard, 360);
    lv_obj_set_align(ui_serverKeyboard, LV_ALIGN_CENTER);

    lv_obj_add_event_cb(ui_serverAddressTextArea, ui_event_serverAddressTextArea, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_serverPwTextArea, ui_event_serverPwTextArea, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_serverSetButton, ui_event_serverSetButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_serverBackButton, ui_event_serverBackButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_serverScreen, ui_event_serverScreen, LV_EVENT_ALL, NULL);

}

void ui_serverScreen_screen_destroy(void)
{
    if(ui_serverScreen) lv_obj_del(ui_serverScreen);

    // NULL screen variables
    ui_serverScreen = NULL;
    ui_serverLabel = NULL;
    ui_serverTextArea = NULL;
    ui_serverAddressContainer = NULL;
    ui_serverAddressLabel = NULL;
    ui_serverAddressTextArea = NULL;
    ui_serverPwContainer = NULL;
    ui_serverPwLabel = NULL;
    ui_serverPwTextArea = NULL;
    ui_serverSetButton = NULL;
    ui_serverSetLabel = NULL;
    ui_serverBackButton = NULL;
    ui_serverBackImage = NULL;
    ui_serverKeyboard = NULL;

}
