// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: sql-coffee-candy

#ifndef UI_WIFISCREEN_H
#define UI_WIFISCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_wifiScreen
extern void ui_wifiScreen_screen_init(void);
extern void ui_wifiScreen_screen_destroy(void);
extern void ui_event_wifiScreen(lv_event_t * e);
extern lv_obj_t * ui_wifiScreen;
extern lv_obj_t * ui_wifiInfoContainer;
extern lv_obj_t * ui_wifiInfoLabel;
extern lv_obj_t * ui_wifiInfoImage;
extern lv_obj_t * ui_wifiTextArea;
extern lv_obj_t * ui_wifiSsidContainer;
extern lv_obj_t * ui_wifiSsidLabel;
extern void ui_event_wifiSsidTextArea(lv_event_t * e);
extern lv_obj_t * ui_wifiSsidTextArea;
extern lv_obj_t * ui_wifiPwContainer;
extern lv_obj_t * ui_wifiPwLabel;
extern void ui_event_wifiPwTextArea(lv_event_t * e);
extern lv_obj_t * ui_wifiPwTextArea;
extern void ui_event_wifiConnectButton(lv_event_t * e);
extern lv_obj_t * ui_wifiConnectButton;
extern lv_obj_t * ui_wifiConnectLabel;
extern void ui_event_wifiRestoreButton(lv_event_t * e);
extern lv_obj_t * ui_wifiRestoreButton;
extern lv_obj_t * ui_wifiRestoreLabel;
extern void ui_event_wifiBackButton(lv_event_t * e);
extern lv_obj_t * ui_wifiBackButton;
extern lv_obj_t * ui_wifiBackImage;
extern lv_obj_t * ui_wifiKeyboard;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

