// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: sql-coffee-candy

#include "ui.h"

lv_obj_t * ui_wifiScreen = NULL;
lv_obj_t * ui_wifiInfoContainer = NULL;
lv_obj_t * ui_wifiInfoLabel = NULL;
lv_obj_t * ui_wifiInfoImage = NULL;
lv_obj_t * ui_wifiTextArea = NULL;
lv_obj_t * ui_wifiSsidContainer = NULL;
lv_obj_t * ui_wifiSsidLabel = NULL;
lv_obj_t * ui_wifiSsidTextArea = NULL;
lv_obj_t * ui_wifiPwContainer = NULL;
lv_obj_t * ui_wifiPwLabel = NULL;
lv_obj_t * ui_wifiPwTextArea = NULL;
lv_obj_t * ui_wifiConnectButton = NULL;
lv_obj_t * ui_wifiConnectLabel = NULL;
lv_obj_t * ui_wifiRestoreButton = NULL;
lv_obj_t * ui_wifiRestoreLabel = NULL;
lv_obj_t * ui_wifiBackButton = NULL;
lv_obj_t * ui_wifiBackImage = NULL;
lv_obj_t * ui_wifiKeyboard = NULL;
// event funtions
void ui_event_wifiScreen(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOAD_START) {
        wifi_screen_load(e);
    }
}

void ui_event_wifiSsidTextArea(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_FOCUSED) {
        keyboardUpAnimation_Animation(ui_wifiKeyboard, 0);
        _ui_keyboard_set_target(ui_wifiKeyboard,  ui_wifiSsidTextArea);
    }
    if(event_code == LV_EVENT_DEFOCUSED) {
        keyboardDownAnimation_Animation(ui_wifiKeyboard, 0);
    }
}

void ui_event_wifiPwTextArea(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_FOCUSED) {
        keyboardUpAnimation_Animation(ui_wifiKeyboard, 0);
        _ui_keyboard_set_target(ui_wifiKeyboard,  ui_wifiPwTextArea);
    }
    if(event_code == LV_EVENT_DEFOCUSED) {
        keyboardDownAnimation_Animation(ui_wifiKeyboard, 0);
    }
}

void ui_event_wifiConnectButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_RELEASED) {
        wifi_connect(e);
    }
}

void ui_event_wifiRestoreButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_RELEASED) {
        wifi_restore(e);
    }
}

void ui_event_wifiBackButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_RELEASED) {
        _ui_screen_change(&ui_configScreen, LV_SCR_LOAD_ANIM_OVER_BOTTOM, 500, 0, &ui_configScreen_screen_init);
        _ui_screen_delete(&ui_wifiScreen);
    }
}

// build funtions

void ui_wifiScreen_screen_init(void)
{
    ui_wifiScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_wifiScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_wifiInfoContainer = lv_obj_create(ui_wifiScreen);
    lv_obj_remove_style_all(ui_wifiInfoContainer);
    lv_obj_set_width(ui_wifiInfoContainer, 380);
    lv_obj_set_height(ui_wifiInfoContainer, 50);
    lv_obj_set_x(ui_wifiInfoContainer, -200);
    lv_obj_set_y(ui_wifiInfoContainer, -205);
    lv_obj_set_align(ui_wifiInfoContainer, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_wifiInfoContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_wifiInfoLabel = lv_label_create(ui_wifiInfoContainer);
    lv_obj_set_width(ui_wifiInfoLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_wifiInfoLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_wifiInfoLabel, -30);
    lv_obj_set_y(ui_wifiInfoLabel, 0);
    lv_obj_set_align(ui_wifiInfoLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_wifiInfoLabel, "Wi-Fi: No Connection");
    lv_obj_set_style_text_font(ui_wifiInfoLabel, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_wifiInfoImage = lv_img_create(ui_wifiInfoContainer);
    lv_obj_set_width(ui_wifiInfoImage, 50);
    lv_obj_set_height(ui_wifiInfoImage, 50);
    lv_obj_set_x(ui_wifiInfoImage, 165);
    lv_obj_set_y(ui_wifiInfoImage, 0);
    lv_obj_set_align(ui_wifiInfoImage, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_wifiInfoImage, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_wifiInfoImage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_wifiTextArea = lv_textarea_create(ui_wifiScreen);
    lv_obj_set_width(ui_wifiTextArea, 380);
    lv_obj_set_height(ui_wifiTextArea, 400);
    lv_obj_set_x(ui_wifiTextArea, -200);
    lv_obj_set_y(ui_wifiTextArea, 30);
    lv_obj_set_align(ui_wifiTextArea, LV_ALIGN_CENTER);

    ui_wifiSsidContainer = lv_obj_create(ui_wifiScreen);
    lv_obj_remove_style_all(ui_wifiSsidContainer);
    lv_obj_set_width(ui_wifiSsidContainer, 380);
    lv_obj_set_height(ui_wifiSsidContainer, 50);
    lv_obj_set_x(ui_wifiSsidContainer, 195);
    lv_obj_set_y(ui_wifiSsidContainer, -155);
    lv_obj_set_align(ui_wifiSsidContainer, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_wifiSsidContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_wifiSsidLabel = lv_label_create(ui_wifiSsidContainer);
    lv_obj_set_width(ui_wifiSsidLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_wifiSsidLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_wifiSsidLabel, -150);
    lv_obj_set_y(ui_wifiSsidLabel, 0);
    lv_obj_set_align(ui_wifiSsidLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_wifiSsidLabel, "SSID");
    lv_obj_set_style_text_font(ui_wifiSsidLabel, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_wifiSsidTextArea = lv_textarea_create(ui_wifiSsidContainer);
    lv_obj_set_width(ui_wifiSsidTextArea, 300);
    lv_obj_set_height(ui_wifiSsidTextArea, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(ui_wifiSsidTextArea, 40);
    lv_obj_set_y(ui_wifiSsidTextArea, 0);
    lv_obj_set_align(ui_wifiSsidTextArea, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_wifiSsidTextArea, "SSID");
    lv_textarea_set_one_line(ui_wifiSsidTextArea, true);

    ui_wifiPwContainer = lv_obj_create(ui_wifiScreen);
    lv_obj_remove_style_all(ui_wifiPwContainer);
    lv_obj_set_width(ui_wifiPwContainer, 380);
    lv_obj_set_height(ui_wifiPwContainer, 50);
    lv_obj_set_x(ui_wifiPwContainer, 195);
    lv_obj_set_y(ui_wifiPwContainer, -55);
    lv_obj_set_align(ui_wifiPwContainer, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_wifiPwContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_wifiPwLabel = lv_label_create(ui_wifiPwContainer);
    lv_obj_set_width(ui_wifiPwLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_wifiPwLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_wifiPwLabel, -150);
    lv_obj_set_y(ui_wifiPwLabel, 0);
    lv_obj_set_align(ui_wifiPwLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_wifiPwLabel, "PW");
    lv_obj_set_style_text_font(ui_wifiPwLabel, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_wifiPwTextArea = lv_textarea_create(ui_wifiPwContainer);
    lv_obj_set_width(ui_wifiPwTextArea, 300);
    lv_obj_set_height(ui_wifiPwTextArea, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(ui_wifiPwTextArea, 40);
    lv_obj_set_y(ui_wifiPwTextArea, 0);
    lv_obj_set_align(ui_wifiPwTextArea, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_wifiPwTextArea, "PW");
    lv_textarea_set_one_line(ui_wifiPwTextArea, true);
    lv_textarea_set_password_mode(ui_wifiPwTextArea, true);

    ui_wifiConnectButton = lv_btn_create(ui_wifiScreen);
    lv_obj_set_width(ui_wifiConnectButton, 300);
    lv_obj_set_height(ui_wifiConnectButton, 70);
    lv_obj_set_x(ui_wifiConnectButton, 195);
    lv_obj_set_y(ui_wifiConnectButton, 50);
    lv_obj_set_align(ui_wifiConnectButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_wifiConnectButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_wifiConnectButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_wifiConnectButton, lv_color_hex(0xE8E8E8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_wifiConnectButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_wifiConnectButton, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_wifiConnectButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_wifiConnectButton, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_wifiConnectButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_wifiConnectLabel = lv_label_create(ui_wifiConnectButton);
    lv_obj_set_width(ui_wifiConnectLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_wifiConnectLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_wifiConnectLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_wifiConnectLabel, "CONNECT");
    lv_obj_set_style_text_color(ui_wifiConnectLabel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_wifiConnectLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_wifiConnectLabel, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_wifiRestoreButton = lv_btn_create(ui_wifiScreen);
    lv_obj_set_width(ui_wifiRestoreButton, 200);
    lv_obj_set_height(ui_wifiRestoreButton, 30);
    lv_obj_set_x(ui_wifiRestoreButton, 195);
    lv_obj_set_y(ui_wifiRestoreButton, 150);
    lv_obj_set_align(ui_wifiRestoreButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_wifiRestoreButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_wifiRestoreButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_wifiRestoreButton, lv_color_hex(0xE8E8E8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_wifiRestoreButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_wifiRestoreButton, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_wifiRestoreButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_wifiRestoreButton, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_wifiRestoreButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_wifiRestoreLabel = lv_label_create(ui_wifiRestoreButton);
    lv_obj_set_width(ui_wifiRestoreLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_wifiRestoreLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_wifiRestoreLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_wifiRestoreLabel, "Restore last connection");
    lv_obj_set_style_text_color(ui_wifiRestoreLabel, lv_color_hex(0x404040), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_wifiRestoreLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_wifiBackButton = lv_btn_create(ui_wifiScreen);
    lv_obj_set_width(ui_wifiBackButton, 60);
    lv_obj_set_height(ui_wifiBackButton, 60);
    lv_obj_set_x(ui_wifiBackButton, 360);
    lv_obj_set_y(ui_wifiBackButton, 200);
    lv_obj_set_align(ui_wifiBackButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_wifiBackButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_wifiBackButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_wifiBackButton, lv_color_hex(0xE8E8E8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_wifiBackButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_wifiBackButton, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_wifiBackButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_wifiBackButton, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_wifiBackButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_wifiBackImage = lv_img_create(ui_wifiBackButton);
    lv_obj_set_width(ui_wifiBackImage, 50);
    lv_obj_set_height(ui_wifiBackImage, 50);
    lv_obj_set_align(ui_wifiBackImage, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_wifiBackImage, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_wifiBackImage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_wifiKeyboard = lv_keyboard_create(ui_wifiScreen);
    lv_obj_set_width(ui_wifiKeyboard, 800);
    lv_obj_set_height(ui_wifiKeyboard, 240);
    lv_obj_set_x(ui_wifiKeyboard, 0);
    lv_obj_set_y(ui_wifiKeyboard, 360);
    lv_obj_set_align(ui_wifiKeyboard, LV_ALIGN_CENTER);

    lv_obj_add_event_cb(ui_wifiSsidTextArea, ui_event_wifiSsidTextArea, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_wifiPwTextArea, ui_event_wifiPwTextArea, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_wifiConnectButton, ui_event_wifiConnectButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_wifiRestoreButton, ui_event_wifiRestoreButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_wifiBackButton, ui_event_wifiBackButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_wifiScreen, ui_event_wifiScreen, LV_EVENT_ALL, NULL);

}

void ui_wifiScreen_screen_destroy(void)
{
    if(ui_wifiScreen) lv_obj_del(ui_wifiScreen);

    // NULL screen variables
    ui_wifiScreen = NULL;
    ui_wifiInfoContainer = NULL;
    ui_wifiInfoLabel = NULL;
    ui_wifiInfoImage = NULL;
    ui_wifiTextArea = NULL;
    ui_wifiSsidContainer = NULL;
    ui_wifiSsidLabel = NULL;
    ui_wifiSsidTextArea = NULL;
    ui_wifiPwContainer = NULL;
    ui_wifiPwLabel = NULL;
    ui_wifiPwTextArea = NULL;
    ui_wifiConnectButton = NULL;
    ui_wifiConnectLabel = NULL;
    ui_wifiRestoreButton = NULL;
    ui_wifiRestoreLabel = NULL;
    ui_wifiBackButton = NULL;
    ui_wifiBackImage = NULL;
    ui_wifiKeyboard = NULL;

}
